name: Build, release and publish
on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
      - '*.x'
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - closed
    paths-ignore:
      - '**.md'

jobs:
  release:
    name: Build, release and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          package-manager-cache: false
      - name: Setup corepack
        run: corepack enable
      - name: Setup semantic-release
        run: yarn install
      - name: Pre Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e ./pre-release.js
      - name: Inject VERSION into workflow
        run: |
          echo VERSION=$(cat VERSION) >> $GITHUB_ENV
        shell: bash
      - name: Check for a bump
        id: bump
        continue-on-error: true
        run: git diff --exit-code VERSION
      - name: Login to GitHub Container Registry
        if: ${{ success() && steps.bump.outcome == 'failure' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        if: ${{ success() && steps.bump.outcome == 'failure' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=v${{ env.VERSION }}
      - name: Docker build and publish
        if: ${{ success() && steps.bump.outcome == 'failure' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: false
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Publish GitHub Release on bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e ./release.js
